"""Cross-page responsive layout smoke tests (CSS viewport, not device detection).

The HTML is generated by prerender.py. Browser navigation may be blocked in CI,
so load the exact page source and its local scripts into an isolated document.
"""
from pathlib import Path
import os
import re
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
PAGES = ['index','research','reading','publications','supervision','people','teaching','software','about','contact']
WIDTHS = [320,360,390,430,600,700,768,820,900,1024,1180,1181,1280,1366,1440,1920,2560]
CSS = (ROOT/'assets/site.css').read_text(encoding='utf-8')
ERRORS = []

def load(browser, name, width=390, height=844):
    page = browser.new_page(viewport={'width':width,'height':height},device_scale_factor=1)
    page.on('pageerror', lambda error: ERRORS.append((name,str(error))))
    html = (ROOT/f'{name}.html').read_text(encoding='utf-8')
    scripts = re.findall(r'<script[^>]*src="([^"]+)"[^>]*></script>',html)
    html = re.sub(r'<script[^>]*src="[^"]+"[^>]*></script>','',html)
    html = re.sub(r'<link rel="stylesheet"[^>]*>','',html)
    page.set_content(html,wait_until='load')
    page.add_style_tag(content=CSS)
    for script in scripts:
        page.add_script_tag(content=(ROOT/script).read_text(encoding='utf-8'))
    page.locator('main h1').first.wait_for(timeout=7000)
    return page

def dimensions(page):
    return page.evaluate('''() => ({
        available: innerWidth,
        page: document.documentElement.scrollWidth,
        shell: document.querySelector('.shell')?.getBoundingClientRect().width || 0,
        h1: document.querySelector('main h1')?.getBoundingClientRect().width || 0,
        nav: getComputedStyle(document.querySelector('#main-nav')).display
    })''')

def assert_fits(page, name, width, menu_open=False):
    actual = dimensions(page)
    assert actual['page'] <= actual['available']+1, (name,width,'horizontal overflow',actual)
    assert 0 < actual['h1'] <= actual['available'], (name,width,'invalid heading',actual)
    assert 0 < actual['shell'] <= min(1381,actual['available']), (name,width,'invalid shell',actual)
    assert actual['nav'] == ('flex' if menu_open or width > 970 else 'none'), (name,width,'wrong navigation mode',actual)

with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_BIN') or None,headless=True,args=['--no-sandbox'])
    for name in PAGES:
        page=load(browser,name)
        for width in WIDTHS:
            page.set_viewport_size({'width':width,'height':844})
            assert_fits(page,name,width)
        for language in ['pt-BR','en']:
            page.locator('#language-toggle').click()
            assert page.locator('html').get_attribute('lang') == language
            for width in [320,390]:
                page.set_viewport_size({'width':width,'height':844})
                page.evaluate('() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
                assert_fits(page,name+' '+language,width)
        print(f'RESPONSIVE {name}: {len(WIDTHS)} widths, no overflow, correct menu: PASS')
        page.close()

    reading=load(browser,'reading')
    for width,minimum in [(600,1),(820,2),(1024,2),(1366,3),(1920,3)]:
        reading.set_viewport_size({'width':width,'height':844})
        cells=reading.locator('.reading-track-grid').first.evaluate(
            '(el) => getComputedStyle(el).gridTemplateColumns.split(" ").length')
        assert cells >= minimum, (width,'reading grid',cells,minimum)
        assert_fits(reading,'reading track',width)
    reading.set_viewport_size({'width':390,'height':844})
    reading.locator('#language-toggle').click()
    assert reading.locator('html').get_attribute('lang')=='pt-BR'
    assert_fits(reading,'reading in Portuguese',390)
    reading.evaluate('document.documentElement.style.fontSize="20px"')
    assert_fits(reading,'reading with larger base type',390)
    reading.set_viewport_size({'width':683,'height':844})  # typical half-width / zoomed laptop viewport
    assert_fits(reading,'reading in narrow desktop window',683)
    reading.close()
    print('RESPONSIVE guide cards, Portuguese, larger type and narrow laptop: PASS')

    for name in ['index','reading','teaching','supervision']:
        phone=load(browser,name,width=568,height=320)
        phone.locator('#menu-toggle').click()
        assert phone.locator('#main-nav').is_visible(),name
        position=phone.locator('#main-nav').evaluate('''el => {
            const bounds=el.getBoundingClientRect();
            return {bottom:bounds.bottom,viewport:innerHeight,height:bounds.height,scrollHeight:el.scrollHeight};
        }''')
        assert position['bottom']<=position['viewport']+1, (name,'landscape menu escapes viewport',position)
        assert_fits(phone,name+' landscape',568,menu_open=True)
        phone.close()
    print('RESPONSIVE landscape navigation fits the short viewport: PASS')

    assert not ERRORS,ERRORS
    browser.close()
print('ALL RESPONSIVE CHECKS PASSED')
